/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.view.ui;

import src.controller.Controller;

/**
 *
 * @author lorrany
 */
public class add extends javax.swing.JFrame {

    private Controller c;

    public add(Controller c) {
        this.c = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        permanentButton = new javax.swing.JButton();
        departmentButton = new javax.swing.JButton();
        technicianButton = new javax.swing.JButton();
        substituteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Title.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Cadastrar");
        Title.setPreferredSize(new java.awt.Dimension(360, 36));

        permanentButton.setBackground(new java.awt.Color(33, 150, 243));
        permanentButton.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        permanentButton.setForeground(new java.awt.Color(255, 255, 255));
        permanentButton.setText("Docente Efetivo");
        permanentButton.setPreferredSize(new java.awt.Dimension(159, 50));
        permanentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permanentButtonActionPerformed(evt);
            }
        });

        departmentButton.setBackground(new java.awt.Color(33, 150, 243));
        departmentButton.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        departmentButton.setForeground(new java.awt.Color(255, 255, 255));
        departmentButton.setText("Departamento");
        departmentButton.setPreferredSize(new java.awt.Dimension(159, 50));
        departmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentButtonActionPerformed(evt);
            }
        });

        technicianButton.setBackground(new java.awt.Color(33, 150, 243));
        technicianButton.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        technicianButton.setForeground(new java.awt.Color(255, 255, 255));
        technicianButton.setText("Técnico");
        technicianButton.setPreferredSize(new java.awt.Dimension(159, 50));
        technicianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                technicianButtonActionPerformed(evt);
            }
        });

        substituteButton.setBackground(new java.awt.Color(33, 150, 243));
        substituteButton.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        substituteButton.setForeground(new java.awt.Color(255, 255, 255));
        substituteButton.setText("Docente Substituto");
        substituteButton.setPreferredSize(new java.awt.Dimension(159, 50));
        substituteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substituteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(substituteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(permanentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(technicianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(departmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(technicianButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(permanentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(substituteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void departmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addDepartment(c).setVisible(true);
            }
        });
    }//GEN-LAST:event_departmentButtonActionPerformed

    private void technicianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_technicianButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addTechnician(c).setVisible(true);
            }
        });
    }//GEN-LAST:event_technicianButtonActionPerformed

    private void permanentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permanentButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addPermanent(c).setVisible(true);
            }
        });
    }//GEN-LAST:event_permanentButtonActionPerformed

    private void substituteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substituteButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addSubstitute(c).setVisible(true);
            }
        });
    }//GEN-LAST:event_substituteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton departmentButton;
    private javax.swing.JButton permanentButton;
    private javax.swing.JButton substituteButton;
    private javax.swing.JButton technicianButton;
    // End of variables declaration//GEN-END:variables
}
