/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.view.ui;

import src.controller.Controller;

/**
 *
 * @author lorrany
 */
public class search extends javax.swing.JFrame {

    private Controller c;

    public search(Controller c) {
        this.c = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeButton1 = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        departmentByCodeButton = new javax.swing.JButton();
        departmentByNameButton = new javax.swing.JButton();
        employeeByCodeButton = new javax.swing.JButton();
        employeeByNameButton = new javax.swing.JButton();
        employeeBySalaryButton = new javax.swing.JButton();

        employeeButton1.setBackground(new java.awt.Color(33, 150, 243));
        employeeButton1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        employeeButton1.setForeground(new java.awt.Color(255, 255, 255));
        employeeButton1.setText("Funcionário");
        employeeButton1.setPreferredSize(new java.awt.Dimension(159, 50));
        employeeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Title.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Buscar");
        Title.setPreferredSize(new java.awt.Dimension(360, 36));

        departmentByCodeButton.setBackground(new java.awt.Color(33, 150, 243));
        departmentByCodeButton.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        departmentByCodeButton.setForeground(new java.awt.Color(255, 255, 255));
        departmentByCodeButton.setText("Departamento por código");
        departmentByCodeButton.setPreferredSize(new java.awt.Dimension(159, 50));
        departmentByCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentByCodeButtonActionPerformed(evt);
            }
        });

        departmentByNameButton.setBackground(new java.awt.Color(33, 150, 243));
        departmentByNameButton.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        departmentByNameButton.setForeground(new java.awt.Color(255, 255, 255));
        departmentByNameButton.setText("Departamento por nome");
        departmentByNameButton.setPreferredSize(new java.awt.Dimension(159, 50));
        departmentByNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentByNameButtonActionPerformed(evt);
            }
        });

        employeeByCodeButton.setBackground(new java.awt.Color(33, 150, 243));
        employeeByCodeButton.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        employeeByCodeButton.setForeground(new java.awt.Color(255, 255, 255));
        employeeByCodeButton.setText("Funcionário por código");
        employeeByCodeButton.setPreferredSize(new java.awt.Dimension(159, 50));
        employeeByCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeByCodeButtonActionPerformed(evt);
            }
        });

        employeeByNameButton.setBackground(new java.awt.Color(33, 150, 243));
        employeeByNameButton.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        employeeByNameButton.setForeground(new java.awt.Color(255, 255, 255));
        employeeByNameButton.setText("Funcionário por nome");
        employeeByNameButton.setPreferredSize(new java.awt.Dimension(159, 50));
        employeeByNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeByNameButtonActionPerformed(evt);
            }
        });

        employeeBySalaryButton.setBackground(new java.awt.Color(33, 150, 243));
        employeeBySalaryButton.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        employeeBySalaryButton.setForeground(new java.awt.Color(255, 255, 255));
        employeeBySalaryButton.setText("Funcionário por faixa salarial");
        employeeBySalaryButton.setPreferredSize(new java.awt.Dimension(159, 50));
        employeeBySalaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBySalaryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeBySalaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeByCodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeByNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentByNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentByCodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(departmentByCodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departmentByNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeByCodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeByNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeBySalaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void departmentByCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentByCodeButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchDepartmentByCode(c).setVisible(true);
            }
        });
    }//GEN-LAST:event_departmentByCodeButtonActionPerformed

    private void departmentByNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentByNameButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchDepartmentByName(c).setVisible(true);
            }
        });
    }//GEN-LAST:event_departmentByNameButtonActionPerformed

    private void employeeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeButton1ActionPerformed

    private void employeeByNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeByNameButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchEmployeeByName(c).setVisible(true);
            }
        });
    }//GEN-LAST:event_employeeByNameButtonActionPerformed

    private void employeeByCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeByCodeButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchEmployeeById(c).setVisible(true);
            }
        });
    }//GEN-LAST:event_employeeByCodeButtonActionPerformed

    private void employeeBySalaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBySalaryButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeesBySalaryReport(c).setVisible(true);
            }
        });
    }//GEN-LAST:event_employeeBySalaryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton departmentByCodeButton;
    private javax.swing.JButton departmentByNameButton;
    private javax.swing.JButton employeeButton1;
    private javax.swing.JButton employeeByCodeButton;
    private javax.swing.JButton employeeByNameButton;
    private javax.swing.JButton employeeBySalaryButton;
    // End of variables declaration//GEN-END:variables
}
